#!/usr/bin/env bash
# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Deploy the Fabric Operator CRDs and Fabric Operations Console into the active
# Kind cluster, then write _cfg/console-env.sh with the connection details so
# that run-tests.sh (and any local shell) can source them.
#
# Usage:
#   export KUBECONFIG="$PWD/_cfg/k8s_context.yaml"
#   .github/scripts/deploy-console.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Activate the project virtualenv if present so ansible-playbook uses the
# Python interpreter that has the kubernetes SDK installed.
if [[ -f "${REPO_ROOT}/.venv/bin/activate" ]]; then
    # shellcheck source=/dev/null
    source "${REPO_ROOT}/.venv/bin/activate"
fi

# ---- Configuration -----------------------------------------------------------
CONSOLE_NAMESPACE="${CONSOLE_NAMESPACE:-default}"
CONSOLE_NAME="${CONSOLE_NAME:-hlf-console}"
CONSOLE_EMAIL="${CONSOLE_EMAIL:-admin@example.com}"
CONSOLE_PASSWORD="${CONSOLE_PASSWORD:-password}"
CONSOLE_STORAGE_CLASS="${CONSOLE_STORAGE_CLASS:-standard}"
# arch must match the kubernetes.io/arch label on the Kind node so that the
# IBPConsole spec.arch is satisfiable.  Image tags are always amd64 (handled
# by role defaults) and are independent of this value.
_HOST_UNAME=$(uname -m)
case "${_HOST_UNAME}" in
  x86_64)        _DEFAULT_NODE_ARCH=amd64 ;;
  aarch64|arm64) _DEFAULT_NODE_ARCH=arm64 ;;
  s390x)         _DEFAULT_NODE_ARCH=s390x ;;
  *)             _DEFAULT_NODE_ARCH=amd64 ;;
esac
NODE_ARCH="${NODE_ARCH:-${_DEFAULT_NODE_ARCH}}"

# Derive domain from the host IP (mirrors what fvtest.yml does)
HOST_IP=$(sh "${SCRIPT_DIR}/get-host-ip.sh")
CONSOLE_DOMAIN=$(echo "${HOST_IP}" | tr -s '.' '-').nip.io

API_ENDPOINT="https://${CONSOLE_NAMESPACE}-${CONSOLE_NAME}-console.${CONSOLE_DOMAIN}"

echo "==> Deploying Fabric Operator CRDs and Console"
echo "    namespace : ${CONSOLE_NAMESPACE}"
echo "    name      : ${CONSOLE_NAME}"
echo "    domain    : ${CONSOLE_DOMAIN}"
echo "    endpoint  : ${API_ENDPOINT}"
echo "    arch      : ${NODE_ARCH}"
echo ""

# ---- Deploy via ansible-playbook ---------------------------------------------
ansible-playbook -i localhost, -c local \
  -e k8s_target=k8s \
  -e console_arch="${NODE_ARCH}" \
  -e k8s_namespace="${CONSOLE_NAMESPACE}" \
  -e wait_timeout=600 \
  -e hlf_console_name="${CONSOLE_NAME}" \
  -e hlf_console_domain="${CONSOLE_DOMAIN}" \
  -e console_email="${CONSOLE_EMAIL}" \
  -e console_default_password="${CONSOLE_PASSWORD}" \
  -e console_storage_class="${CONSOLE_STORAGE_CLASS}" \
  "${REPO_ROOT}/tutorial/00-deploy-fabric-console.yml"

# ---- Write connection env file -----------------------------------------------
mkdir -p "${REPO_ROOT}/_cfg"
cat > "${REPO_ROOT}/_cfg/console-env.sh" << ENVEOF
# Auto-generated by deploy-console.sh — source this before running run-tests.sh
export API_ENDPOINT="${API_ENDPOINT}"
export API_AUTHTYPE="basic"
export API_KEY="${CONSOLE_EMAIL}"
export API_SECRET="${CONSOLE_PASSWORD}"
export K8S_NAMESPACE="${CONSOLE_NAMESPACE}"
export KUBECONFIG="${REPO_ROOT}/_cfg/k8s_context.yaml"
ENVEOF

echo ""
echo "==> Console deployed. Connection details written to _cfg/console-env.sh"
echo "    Source it and then run the tests:"
echo "      source _cfg/console-env.sh"
echo "      .github/scripts/run-tests.sh"
